basePath: /
definitions:
  dto.ProxyRequest:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
  dto.ProxyResponse:
    properties:
      headers:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      id:
        type: string
      length:
        type: integer
      status:
        type: integer
      url:
        type: string
    type: object
host: localhost:8181
info:
  contact: {}
  description: Server allows do http requests to another websites
  title: Proxy Server
  version: "1.0"
paths:
  /proxy:
    post:
      consumes:
      - application/json
      description: allows make http request to another website
      parameters:
      - description: request data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.ProxyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ProxyResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "502":
          description: Bad Gateway
          schema:
            type: string
      summary: process requested url
      tags:
      - proxy-controller
  /proxy/{id}:
    get:
      description: return request and response by id
      parameters:
      - description: request id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ProxyResponse'
      summary: get proxy history by id
      tags:
      - proxy-controller
swagger: "2.0"
